on: [push, pull_request]

jobs:
  job:
    runs-on: [ubuntu-18.04]
    steps:
      - name: show_envs
        run: |
          echo GITHUB_ENV: $GITHUB_ENV
          echo ENV: $ENV
          echo GITHUB_REF: $GITHUB_REF
          echo github.ref: ${{ github.ref }}
          echo github.ref_name: ${{ github.ref_name }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.base_ref: ${{ github.base_ref }}

      - name: set_env_dev
        # PR from release-dev
        if: github.base_ref == 'release-dev'
        run: |
          echo ENV=dev >> $GITHUB_ENV
      
      - name: set_env_stg
        # push to release/*
        if: github.event_name == 'push' && contains(github.ref_name, 'release/')
        run: |
          echo ENV=stg >> $GITHUB_ENV
          ls -ltr

      - name: set_env_prd
        # tagging
        if: github.event_name == 'push' && contains(github.ref, '/tags/')
        run: |
          echo ENV=prd >> $GITHUB_ENV

      - name: show_env_re
        if: ${{ env.ENV }}
        run: |
          export ENV=$ENV
          echo ENV: $ENV

      - name: nothing_todo
        if: ${{ env.ENV == '' }}
        run: |
          echo nothing to do!