on:
  release:
    branch:
      - 'master'
    types:
      - published


jobs:
  job:
    runs-on: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: show_envs
        run: |
          echo GITHUB_ENV: $GITHUB_ENV
          echo ENV: $ENV
          echo GITHUB_REF: $GITHUB_REF
          echo github.ref: ${{ github.ref }}
          echo github.ref_name: ${{ github.ref_name }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.base_ref: ${{ github.base_ref }}
          echo github.event_name: ${{ github.event_name }}
          echo github.event.release.target_commitish: {{ github.event.release.target_commitish }}
          echo this is in branch!
          ls -ltr
      
      - name: check_branch
        if: github.event.release.target_commitish != 'master'
        run: | 
          echo abort release!!!
          exit 1
